#!/bin/bash

M=$1
O=$2
if [ "$1" == "-j" ]; then
    M=$2
    O=$1
fi


if [ "$M" == "" ]; then
    MODE=release
elif [ "$M" == "d" ]; then
    MODE=debug
elif [ "$M" == "r" ]; then
    MODE=release
else
    echo "Error: invalid argument"
    exit 1
fi

make $MODE && ./bin/tester.d $O
