#!/bin/bash

if [ "$1" == "" ]; then
    MODE=release
elif [ "$1" == "d" ]; then
    MODE=debug
elif [ "$1" == "r" ]; then
    MODE=release
else
    echo "Error: invalid argument"
    exit 1
fi

make $MODE && ./bin/tester.d
